target:
	gcc -Wall -g -I. -o prog client.c lab07-BSTLibrary/data.c lab07-BSTLibrary/tree.c lab08-HTLibrary/item.c lab08-HTLibrary/st.c util/util.c -lm
	./prog f.txt

clean:
	rm -rf ht
	rm -rf *~
	rm -rf #*
	rm -rf *.bak
